name: Deploy

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: "tdp-linter-test"
  AZURE_WEBAPP_PACKAGE_PATH: "."
  NODE_VERSION: "16.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: npm install, build and test
        run: |
          npm ci
          npm run build --if-present
          npm test

      - name: Upload artifacts for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: "tdp-linter-test"
          path: "."
          target_directory: "."
          artifact_path: "."
          artifact_format: "zip"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url}}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/deploy-to-webapp@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
